apiVersion: v1 
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
# It is always better to override the variables at runtime instead of rebuilding the image as we have hardcoded the env var in image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: pradeepgorle/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080 # Service port
    targetPort: 8080
    
  